[package]
name = "fig_os_shim"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
publish.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
cfg-if.workspace = true
dirs.workspace = true
serde.workspace = true
sysinfo.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["fs", "signal"] }
tracing = { workspace = true }

[target.'cfg(unix)'.dependencies]
sysinfo.workspace = true
nix.workspace = true

[target.'cfg(windows)'.dependencies]
windows = { version = "0.52.0", features = [
    "Win32_Foundation",
    "Win32_System_Threading",
    "Win32_System_ProcessStatus",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_Diagnostics_Debug"
]}
wmi = { version = "0.12.2", default-features = false }

[lints]
workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["fs", "macros", "rt"] }
