[package]
name = "q_chat"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
publish.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
amzn-codewhisperer-streaming-client = { path = "../amzn-codewhisperer-streaming-client" }
amzn-qdeveloper-streaming-client = { path = "../amzn-qdeveloper-streaming-client" }
anyhow = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
camino = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
color-print = { workspace = true }
console = { workspace = true }
crossterm = { workspace = true }
dirs = { workspace = true }
eyre = { workspace = true }
fig_api_client = { path = "../fig_api_client" }
fig_auth = { path = "../fig_auth" }
fig_os_shim = { path = "../fig_os_shim" }
fig_proto = { path = "../fig_proto" }
fig_settings = { path = "../fig_settings" }
fig_telemetry = { path = "../fig_telemetry" }
fig_terminal = { path = "../fig_terminal" }
fig_util = { path = "../fig_util" }
futures = { workspace = true }
http = { workspace = true }
itertools = { workspace = true }
lazy_static = { workspace = true }
once_cell = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
rustyline = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
sha2 = { workspace = true }
tempfile = { workspace = true }
termwiz = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }
which = { workspace = true }

[features]
default = ["auto-terminal"]
auto-terminal = ["unix-terminal", "windows-terminal"]
unix-terminal = []
windows-terminal = []
minimal = []  # No terminal UI
no-tuikit = []

[lints]
workspace = true

[dev-dependencies]
assert_cmd = { workspace = true }
insta = { workspace = true }
predicates = { workspace = true }
rstest = { workspace = true }
serial_test = { workspace = true }
test-case = { workspace = true }
test-context = { workspace = true }
